'use strict';

module.exports = {
  ...require('./base-ai'),
  ...require('./discard-evaluator'),
  ...require('./ai-controller'),
  ...require('./evaluators/call-evaluator'),
  ...require('./evaluators/riichi-evaluator'),
  ...require('./evaluators/defense-evaluator'),
  ...require('./difficulty/easy-policy'),
  ...require('./difficulty/normal-policy'),
  ...require('./difficulty/hard-policy'),
  ...require('./profiles/default'),
  ...require('./special/mode-2p'),
  ...require('./special/mode-3p'),
  ...require('./special/mode-4p'),
  ...require('./support/hand-metrics'),
  ...require('./support/tile-danger'),
  ...require('./support/push-fold'),
  ...require('./support/visible-tiles'),
  ...require('./support/wait-quality'),
  ...require('./support/danger-model'),
  ...require('./support/hard-ev'),
  ...require('./support/hard-push-fold'),
  ...require('./support/hard-defense-tiebreak'),
  ...require('./support/discard-shape'),
  ...require('./support/discard-candidates'),
  ...require('./support/discard-ranking'),
  ...require('./support/hard-discard-review'),
  ...require('./support/hard-candidate-diagnostics'),
  ...require('./support/round-context'),
  ...require('./contracts/ai-input'),
  ...require('./contracts/ai-output')
};
